[display]
compact = false
show_title = true

[style.command_name]
foreground = "red"

[style.example_text]
foreground = "green"

[style.example_code]
foreground = "cyan"

[style.example_variable]
foreground = "blue"
underline = true

[updates]
auto_update = true
